command: workflow
description: Manage GitHub Actions workflows
subcommands:
  - name: list
    description: List workflow files
    parameters:
      - name: all
        type: boolean
        flag: --all
        short: -a
        description: Include disabled workflows

      - name: limit
        type: integer
        flag: --limit
        short: -L
        description: Maximum number of workflows to fetch

      - name: json
        type: array
        item_type: string
        flag: --json
        description: Output JSON with the specified fields

      - name: jq
        type: string
        flag: --jq
        short: -q
        description: Filter JSON output using a jq expression

      - name: template
        type: string
        flag: --template
        short: -t
        description: Format JSON output using a Go template

      - name: repo
        type: string
        flag: --repo
        short: -R
        description: Select repository

  - name: view
    description: View a workflow
    parameters:
      - name: workflow
        type: string
        description: Workflow ID, name, or filename (positional argument)
        positional: true
        required: true

      - name: ref
        type: string
        flag: --ref
        short: -r
        description: Branch or tag name to view

      - name: web
        type: boolean
        flag: --web
        short: -w
        description: Open workflow in the browser

      - name: yaml
        type: boolean
        flag: --yaml
        short: -y
        description: Output workflow YAML

      - name: repo
        type: string
        flag: --repo
        short: -R
        description: Select repository

  - name: run
    description: Run a workflow
    parameters:
      - name: workflow
        type: string
        description: Workflow ID, name, or filename (positional argument)
        positional: true
        required: true

      - name: ref
        type: string
        flag: --ref
        short: -r
        description: Branch or tag name

      - name: field
        type: map
        flag: -F
        description: Add typed parameter in key=value format

      - name: raw_field
        type: map
        flag: -f
        description: Add string parameter in key=value format

      - name: json
        type: boolean
        flag: --json
        description: Read workflow inputs as JSON via STDIN

      - name: repo
        type: string
        flag: --repo
        short: -R
        description: Select repository

  - name: enable
    description: Enable a workflow
    parameters:
      - name: workflow
        type: string
        description: Workflow ID, name, or filename (positional argument)
        positional: true
        required: true

      - name: repo
        type: string
        flag: --repo
        short: -R
        description: Select repository

  - name: disable
    description: Disable a workflow
    parameters:
      - name: workflow
        type: string
        description: Workflow ID, name, or filename (positional argument)
        positional: true
        required: true

      - name: repo
        type: string
        flag: --repo
        short: -R
        description: Select repository
